const { createGlobPatternsForDependencies } = require('@nx/vue/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['selector', '[class*="dark"]'],
  content: [
    join(__dirname, 'index.html'),
    join(
      __dirname,
      'src/**/*!(*.stories|*.spec).{vue,ts,tsx,js,jsx}'
    ),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {
      colors: {
        'secondary-50': 'var(--secondary-color-50)',
        'secondary-100': 'var(--secondary-color-100)',
        'secondary-200': 'var(--secondary-color-200)',
        'secondary-300': 'var(--secondary-color-300)',
        'secondary-400': 'var(--secondary-color-400)',
        'secondary-500': 'var(--secondary-color-500)',
        'secondary-600': 'var(--secondary-color-600)',
        'secondary-700': 'var(--secondary-color-700)',
        'secondary-800': 'var(--secondary-color-800)',
        'secondary-900': 'var(--secondary-color-900)',
        'secondary-950': 'var(--secondary-color-950)',
        'error-50': 'var(--error-color-50)',
        'error-100': 'var(--error-color-100)',
        'error-200': 'var(--error-color-200)',
        'error-300': 'var(--error-color-300)',
        'error-400': 'var(--error-color-400)',
        'error-500': 'var(--error-color-500)',
        'error-600': 'var(--error-color-600)',
        'error-700': 'var(--error-color-700)',
        'error-800': 'var(--error-color-800)',
        'error-900': 'var(--error-color-900)',
        'error-950': 'var(--error-color-950)',
        'warn-50': 'var(--warn-color-50)',
        'warn-100': 'var(--warn-color-100)',
        'warn-200': 'var(--warn-color-200)',
        'warn-300': 'var(--warn-color-300)',
        'warn-400': 'var(--warn-color-400)',
        'warn-500': 'var(--warn-color-500)',
        'warn-600': 'var(--warn-color-600)',
        'warn-700': 'var(--warn-color-700)',
        'warn-800': 'var(--warn-color-800)',
        'warn-900': 'var(--warn-color-900)',
        'warn-950': 'var(--warn-color-950)',
        'success-50': 'var(--success-color-50)',
        'success-100': 'var(--success-color-100)',
        'success-200': 'var(--success-color-200)',
        'success-300': 'var(--success-color-300)',
        'success-400': 'var(--success-color-400)',
        'success-500': 'var(--success-color-500)',
        'success-600': 'var(--success-color-600)',
        'success-700': 'var(--success-color-700)',
        'success-800': 'var(--success-color-800)',
        'success-900': 'var(--success-color-900)',
        'success-950': 'var(--success-color-950)',
      },
    },
  },
  plugins: [require('tailwindcss-primeui')],
};
