name: Deploy Hai local

on: [push]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm ci

      - uses: nrwl/nx-set-shas@v4

#      - name: Build project
#        run: npm run build

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t build

      # Sets the Netlify --prod flag when pushing to main branch
      # If not pushed to main branch, Netlify will generate a preview
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          prod_flag=""
          if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
          netlify deploy \
            --dir apps/pwa-offline/dist \
            --filter @hai/pwa-offline \
            --site ${{ secrets.NETLIFY_HAI_LOCAL_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_HAI_LOCAL_API_TOKEN }} \
            $prod_flag